### ISSUE TITLE
Add a place picker

### ISSUE THREAD

**Issue by filiptronicek** [petrkucerak/deniksracu#18]
In the https://github.com/petrkucerak/deniksracu/blob/main/public/form.html, the way you choose a location for a toilet is you enter in the coordinates, this is information which can be a big hassle to get. I propose we use something like https://github.com/jimutt/svelte-pick-a-place to let the user to choose from a map.

Here is a demo of this library on Codepen:
https://codepen.io/filip_tronicek/pen/QWprKJY

**Comment by petrkucerak** [comment]
I'd like to add more features:

1. Picker from the map (like @filiptronicek wrote)
2. Find the user location by use user GPS (only on phone)
3. Add toilet with place address

@filiptronicek what do you think about these ways?

**Comment by filiptronicek** [comment]
@petrkucerak sounds great, I think those would be nice additions, it would be useful to have something similar to the [Google Maps Places API](https://developers.google.com/maps/documentation/places/web-service/overview).
