### ISSUE TITLE
My toilet doesn't show

### ISSUE THREAD

**Issue by m93a** [petrkucerak/deniksracu#602]
Hey Petr!
First of all, thanks for creating and maintaining this cool project!

I added [an entry](https://github.com/petrkucerak/deniksracu/blob/8b4ac4216189ca9cd3d2b8ca5104f14429b4e383/_toilets/1709219429091.json#L1) for [CostaCoffee on Strossmayer square](https://en.mapy.cz/s/rebudepuna). The [PR](https://github.com/petrkucerak/deniksracu/pull/551) has been merged into main, but when I go to to [deniksracu.cz](https://deniksracu.cz/), I don't see it. Is it a bug?

![image](https://github.com/petrkucerak/deniksracu/assets/1671665/a9a33ade-07d2-43c9-8257-e7e47b24462e)

**Comment by petrkucerak** [comment]
Hello @m93a!
Is the error still persisting for you? I looked at the map and the toilet has already been added.
![image](https://github.com/petrkucerak/deniksracu/assets/45851215/0560432d-e3b4-4ae3-addf-2fef3e424147)
In the project, I have set up quite aggressive caching at the level of DNS servers, so it's possible that the JSON with toilet information hasn't been updated.
If the problem continues, please let me know more information about what device and browser you're using. I'll try to solve it.

**Comment by petrkucerak** [comment]
Hello @m93a!
Is the error still persisting for you? I looked at the map and the toilet has already been added.
![image](https://github.com/petrkucerak/deniksracu/assets/45851215/0560432d-e3b4-4ae3-addf-2fef3e424147)
In the project, I have set up quite aggressive caching at the level of DNS servers, so it's possible that the JSON with toilet information hasn't been updated.
If the problem continues, please let me know more information about what device and browser you're using. I'll try to solve it.
